import type { Week } from "./types";

// These starter entries establish the structure of a research notebook. Edit
// them from /adminzzz, then publish an entry when it is ready to share.
export const weeks: Week[] = [
  {
    id: "entry-1",
    number: 1,
    slug: "research-map",
    title: "Research map",
    summary: "A living index of the questions, themes and papers that shape this research journey.",
    objectives: [
      "Record the central questions guiding the work.",
      "Link each topic to its most useful papers and notes.",
      "Keep a clear trail from early ideas to finished writing.",
    ],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      {
        id: "map-welcome",
        type: "text",
        heading: "Welcome to the research journey",
        body: "This is a personal space for following ideas over time: collecting questions, reading papers closely, testing connections and sharing work when it is ready.\n\nStart here with the themes that matter most. Each entry can become a topic note, a paper reading, a working draft or a published piece.",
      },
      {
        id: "map-note",
        type: "callout",
        tone: "note",
        heading: "How to use this site",
        body: "Use the editor at /adminzzz to add a topic, attach a paper or write a reflection. Save a draft while it is still evolving; publish it when you want it to appear in the public reading list.",
      },
      {
        id: "map-themes",
        type: "table",
        heading: "Themes to explore",
        tableHeaders: ["Theme", "Guiding question", "Current status"],
        tableRows: [
          ["Topic one", "What do I want to understand?", "Collecting sources"],
          ["Topic two", "What relationship is worth testing?", "Notes in progress"],
          ["Topic three", "What could this contribute?", "Open question"],
        ],
      },
    ],
  },
  {
    id: "entry-2",
    number: 2,
    slug: "reading-notes",
    title: "Reading notes",
    summary: "A place for careful paper summaries, useful quotations and questions that remain after reading.",
    objectives: [
      "Capture the paper’s argument in your own words.",
      "Note evidence, methods and limitations.",
      "Connect the reading to the wider research map.",
    ],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      {
        id: "reading-start",
        type: "text",
        heading: "A reading template",
        body: "For every paper, begin with a short summary of its question and claim. Then record what evidence it uses, what it makes clearer, and what you would like to investigate next.\n\nReplace this starter entry with your first paper, or add a new entry from the editor.",
      },
      {
        id: "reading-paper",
        type: "resource",
        heading: "Paper or source",
        title: "Add a paper here",
        body: "Include a concise note explaining why this source matters to your research.",
        url: "https://example.com",
      },
    ],
  },
  {
    id: "entry-3",
    number: 3,
    slug: "working-papers",
    title: "Working papers",
    summary: "Draft ideas, methods and early writing that may later become a paper or project.",
    objectives: [
      "Develop an argument through small, dated iterations.",
      "Keep methods and evidence close to the draft.",
      "Publish a clear version when the work is ready.",
    ],
    study: { definitions: [], questions: [] },
    status: "draft",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      {
        id: "working-start",
        type: "text",
        heading: "Work in progress",
        body: "This entry is private until you publish it. Use it to hold a developing outline, a research method, an abstract or a paper draft.",
      },
    ],
  },
  {
    id: "paper-1",
    number: 4,
    slug: "breaking-information-silos-smart-metro-security",
    title: "Breaking Information Silos in Smart Metro Security",
    summary: "An edge-cloud collaborative AIoT framework with humanoid agents.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-1-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: To be added\n\nSummary: A smart-metro security demonstration with one humanoid robot. The robot uses a YOLO-based vision pipeline to relate a passenger to a bag or other carried item, then helps decide whether a recheck is needed. The idea is intentionally practical rather than complicated: connect existing checkpoint signals to one robot that can guide a passenger when something looks unusual." },
      { id: "paper-1-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/breaking-information-silos-smart-metro-security.pdf" },
      { id: "paper-1-status", type: "status", status: "yellow", body: "In progress — questions remain" },
      { id: "paper-1-notes", type: "text", heading: "My summary", body: "The paper’s real contribution is the system integration around the robot. It connects X-ray cues, the robot camera, a combined safety score and a task scheduler so that the single humanoid can speak, gesture, show warnings or direct a passenger to recheck. Its vision method begins with YOLOv8-Pose and DeepSORT, then adds keypoint-guided attention and a carrying-state classifier to distinguish bags that are genuinely being carried from implausible or poorly associated detections. In that sense, the humanoid is mainly the physical interface for a smart checkpoint rather than an autonomous security decision-maker." },
      { id: "paper-1-flow", type: "mermaid", heading: "How the checkpoint loop works", body: "flowchart LR\n  A[Passenger and bag] --> B[Robot camera\nYOLOv8-Pose + tracking]\n  A --> C[X-ray and metal detector]\n  B --> D[Safety-score fusion]\n  C --> D\n  D --> E[Task scheduler]\n  E --> F[One humanoid robot\nvoice, gesture, warning]\n  F --> G[Guide or recheck passenger]" },
      { id: "paper-1-network", type: "text", heading: "Is networking a major part?", body: "Networking is included, but it is not the paper’s deepest contribution. The humanoid is presented as the edge node: EtherCAT controls its joints with a stated cycle time below 1 ms, while MQTT carries higher-level events between perception and decision modules. The paper uses the network to connect the X-ray machine, metal detector, robot vision and task scheduler. It does not propose a new networking protocol, Open RAN design or communication algorithm; the network is mainly enabling infrastructure for the application." },
      { id: "paper-1-latency-math", type: "text", heading: "Latency and mathematical complexity", body: "Yes, the paper discusses latency. It separates visual, X-ray and fusion-triggered paths, reporting maximum measured end-to-end latencies of 162.1 ms, 269.7 ms and 271.3 ms respectively. Under injected MQTT packet loss and jitter, the vision-triggered latency rises from 138.7 ms to 215.4 ms. The maths is not especially difficult: it mostly defines the safety score, scheduling priorities and latency as sums of component delays. The work is primarily an applied systems paper, rather than a theory-heavy machine-learning or networking paper." },
      { id: "paper-1-accuracy", type: "text", heading: "Accuracy and limits", body: "The paper does not report one simple overall accuracy. On its 3,600-image test set across six object-state labels, the proposed visual method reports 46.9% average precision (AP), 69.4% AP50, 49.7% AP75 and 60.1% average recall. The authors report a 10.5 percentage-point AP improvement over YOLOv8-s. For the combined X-ray and vision safety score, they report an AUC of 0.92, compared with 0.76 for vision-only, and at their selected recheck threshold a 96.5% true-positive rate with a 4.2% false-positive rate. These results are promising for the tested setup, but the dataset and trained models are not public, so independent reproduction is not currently possible." },
      { id: "paper-1-verdict", type: "callout", tone: "warning", heading: "Verdict", body: "This is a mid-level paper: useful as a concrete smart-metro integration example, but not especially interesting for a deep research direction. Its value is showing one humanoid robot connected to existing sensors and workflows; the novelty and evaluation should be treated cautiously because the data and trained models are not public." },
    ],
  },
  {
    id: "paper-2",
    number: 5,
    slug: "finite-memory-cooperative-localization-humanoid-robots",
    title: "Finite-Memory CL for Multiple Humanoid Robots",
    summary: "Multisensor information fusion using neural networks.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-2-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: To be added\n\nSummary: To be added" },
      { id: "paper-2-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/finite-memory-cl-multisensor-humanoid-robots.pdf" },
      { id: "paper-2-status", type: "status", status: "red", body: "Not read yet" },
      { id: "paper-2-notes", type: "text", heading: "Notes", body: "Add reading notes, questions and useful connections here." },
    ],
  },
  {
    id: "paper-3",
    number: 6,
    slug: "o-races-open-ran-6g-humanoid-robots",
    title: "O-RACES",
    summary: "Proactive AI-driven scheduling in Open RAN for 6G-networked humanoid robots.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-3-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: O-RACES\n\nSummary: To be added" },
      { id: "paper-3-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/o-races-open-ran-6g-humanoid-robots.pdf" },
      { id: "paper-3-status", type: "status", status: "red", body: "Not read yet" },
      { id: "paper-3-notes", type: "text", heading: "Notes", body: "Add reading notes, questions and useful connections here." },
    ],
  },
  {
    id: "paper-4",
    number: 7,
    slug: "iot-humanoid-robot-review",
    title: "Use of Internet of Things in a Humanoid Robot",
    summary: "A review of the use of IoT in humanoid robots.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-4-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: To be added\n\nSummary: To be added" },
      { id: "paper-4-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/iot-humanoid-robot-review.pdf" },
      { id: "paper-4-status", type: "status", status: "red", body: "Not read yet" },
      { id: "paper-4-notes", type: "text", heading: "Notes", body: "Add reading notes, questions and useful connections here." },
    ],
  },
  {
    id: "paper-5",
    number: 8,
    slug: "internet-of-humanoids-survey",
    title: "The Internet of Humanoids",
    summary: "A survey of technologies, applications and challenges.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-5-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: IoH\n\nSummary: To be added" },
      { id: "paper-5-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/internet-of-humanoids-survey.pdf" },
      { id: "paper-5-status", type: "status", status: "red", body: "Not read yet" },
      { id: "paper-5-notes", type: "text", heading: "Notes", body: "Add reading notes, questions and useful connections here." },
    ],
  },
  {
    id: "paper-6",
    number: 9,
    slug: "vision-language-models-edge-robotic-perception",
    title: "Vision-Language Models on the Edge",
    summary: "Real-time robotic perception with edge-deployed vision-language models.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-6-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: VLMs\n\nSummary: To be added" },
      { id: "paper-6-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/vision-language-models-edge-robotic-perception.pdf" },
      { id: "paper-6-status", type: "status", status: "red", body: "Not read yet" },
      { id: "paper-6-notes", type: "text", heading: "Notes", body: "Add reading notes, questions and useful connections here." },
    ],
  },
];
