import type { Week } from "./types";

// These starter entries establish the structure of a research notebook. Edit
// them from /adminzzz, then publish an entry when it is ready to share.
export const weeks: Week[] = [
  {
    id: "entry-1",
    number: 1,
    slug: "research-map",
    title: "Research map",
    summary: "A living index of the questions, themes and papers that shape this research journey.",
    objectives: [
      "Record the central questions guiding the work.",
      "Link each topic to its most useful papers and notes.",
      "Keep a clear trail from early ideas to finished writing.",
    ],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      {
        id: "map-welcome",
        type: "text",
        heading: "Welcome to the research journey",
        body: "This is a personal space for following ideas over time: collecting questions, reading papers closely, testing connections and sharing work when it is ready.\n\nStart here with the themes that matter most. Each entry can become a topic note, a paper reading, a working draft or a published piece.",
      },
      {
        id: "map-note",
        type: "callout",
        tone: "note",
        heading: "How to use this site",
        body: "Use the editor at /adminzzz to add a topic, attach a paper or write a reflection. Save a draft while it is still evolving; publish it when you want it to appear in the public reading list.",
      },
      {
        id: "map-themes",
        type: "table",
        heading: "Themes to explore",
        tableHeaders: ["Theme", "Guiding question", "Current status"],
        tableRows: [
          ["Topic one", "What do I want to understand?", "Collecting sources"],
          ["Topic two", "What relationship is worth testing?", "Notes in progress"],
          ["Topic three", "What could this contribute?", "Open question"],
        ],
      },
    ],
  },
  {
    id: "entry-2",
    number: 2,
    slug: "reading-notes",
    title: "Reading notes",
    summary: "A place for careful paper summaries, useful quotations and questions that remain after reading.",
    objectives: [
      "Capture the paper’s argument in your own words.",
      "Note evidence, methods and limitations.",
      "Connect the reading to the wider research map.",
    ],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      {
        id: "reading-start",
        type: "text",
        heading: "A reading template",
        body: "For every paper, begin with a short summary of its question and claim. Then record what evidence it uses, what it makes clearer, and what you would like to investigate next.\n\nReplace this starter entry with your first paper, or add a new entry from the editor.",
      },
      {
        id: "reading-paper",
        type: "resource",
        heading: "Paper or source",
        title: "Add a paper here",
        body: "Include a concise note explaining why this source matters to your research.",
        url: "https://example.com",
      },
    ],
  },
  {
    id: "entry-3",
    number: 3,
    slug: "working-papers",
    title: "Working papers",
    summary: "Draft ideas, methods and early writing that may later become a paper or project.",
    objectives: [
      "Develop an argument through small, dated iterations.",
      "Keep methods and evidence close to the draft.",
      "Publish a clear version when the work is ready.",
    ],
    study: { definitions: [], questions: [] },
    status: "draft",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      {
        id: "working-start",
        type: "text",
        heading: "Work in progress",
        body: "This entry is private until you publish it. Use it to hold a developing outline, a research method, an abstract or a paper draft.",
      },
    ],
  },
  {
    id: "paper-1",
    number: 4,
    slug: "breaking-information-silos-smart-metro-security",
    title: "Breaking Information Silos in Smart Metro Security",
    summary: "An edge-cloud collaborative AIoT framework with humanoid agents.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-1-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: To be added\n\nSummary: A smart-metro security demonstration with one humanoid robot. The robot uses a YOLO-based vision pipeline to relate a passenger to a bag or other carried item, then helps decide whether a recheck is needed. The idea is intentionally practical rather than complicated: connect existing checkpoint signals to one robot that can guide a passenger when something looks unusual." },
      { id: "paper-1-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/breaking-information-silos-smart-metro-security.pdf" },
      { id: "paper-1-status", type: "status", status: "yellow", body: "In progress — questions remain" },
      { id: "paper-1-notes", type: "text", heading: "My summary", body: "The paper’s real contribution is the system integration around the robot. It connects X-ray cues, the robot camera, a combined safety score and a task scheduler so that the single humanoid can speak, gesture, show warnings or direct a passenger to recheck. Its vision method begins with YOLOv8-Pose and DeepSORT, then adds keypoint-guided attention and a carrying-state classifier to distinguish bags that are genuinely being carried from implausible or poorly associated detections. In that sense, the humanoid is mainly the physical interface for a smart checkpoint rather than an autonomous security decision-maker." },
      { id: "paper-1-flow", type: "mermaid", heading: "How the checkpoint loop works", body: "flowchart LR\n  A[Passenger and bag] --> B[Robot camera\nYOLOv8-Pose + tracking]\n  A --> C[X-ray and metal detector]\n  B --> D[Safety-score fusion]\n  C --> D\n  D --> E[Task scheduler]\n  E --> F[One humanoid robot\nvoice, gesture, warning]\n  F --> G[Guide or recheck passenger]" },
      { id: "paper-1-network", type: "text", heading: "Is networking a major part?", body: "Networking is included, but it is not the paper’s deepest contribution. The humanoid is presented as the edge node: EtherCAT controls its joints with a stated cycle time below 1 ms, while MQTT carries higher-level events between perception and decision modules. The paper uses the network to connect the X-ray machine, metal detector, robot vision and task scheduler. It does not propose a new networking protocol, Open RAN design or communication algorithm; the network is mainly enabling infrastructure for the application." },
      { id: "paper-1-latency-math", type: "text", heading: "Latency and mathematical complexity", body: "Yes, the paper discusses latency. It separates visual, X-ray and fusion-triggered paths, reporting maximum measured end-to-end latencies of 162.1 ms, 269.7 ms and 271.3 ms respectively. Under injected MQTT packet loss and jitter, the vision-triggered latency rises from 138.7 ms to 215.4 ms. The maths is not especially difficult: it mostly defines the safety score, scheduling priorities and latency as sums of component delays. The work is primarily an applied systems paper, rather than a theory-heavy machine-learning or networking paper." },
      { id: "paper-1-accuracy", type: "text", heading: "Accuracy and limits", body: "The paper does not report one simple overall accuracy. On its 3,600-image test set across six object-state labels, the proposed visual method reports 46.9% average precision (AP), 69.4% AP50, 49.7% AP75 and 60.1% average recall. The authors report a 10.5 percentage-point AP improvement over YOLOv8-s. For the combined X-ray and vision safety score, they report an AUC of 0.92, compared with 0.76 for vision-only, and at their selected recheck threshold a 96.5% true-positive rate with a 4.2% false-positive rate. These results are promising for the tested setup, but the dataset and trained models are not public, so independent reproduction is not currently possible." },
      { id: "paper-1-verdict", type: "callout", tone: "warning", heading: "Verdict", body: "This is a mid-level paper: useful as a concrete smart-metro integration example, but not especially interesting for a deep research direction. Its value is showing one humanoid robot connected to existing sensors and workflows; the novelty and evaluation should be treated cautiously because the data and trained models are not public." },
    ],
  },
  {
    id: "paper-2",
    number: 5,
    slug: "finite-memory-cooperative-localization-humanoid-robots",
    title: "Finite-Memory CL for Multiple Humanoid Robots",
    summary: "Multisensor information fusion using neural networks.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-2-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: OAFMCL (odometry-aided finite-memory cooperative localization)\n\nSummary: This is a multi-humanoid localization paper, but the experiment uses three robots - one leader and two followers - not four or five. The leader has a better absolute-position sensor; followers use lower-cost sensors and can improve their own position estimate by combining their measurements with positions received from neighbouring robots." },
      { id: "paper-2-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/finite-memory-cl-multisensor-humanoid-robots.pdf" },
      { id: "paper-2-status", type: "status", status: "yellow", body: "In progress — questions remain" },
      { id: "paper-2-summary", type: "text", heading: "My summary", body: "The paper studies three BIOLOID humanoids moving in a 4.5 m × 4.5 m indoor square. Robot 2 is the leader and Robots 1 and 3 are followers. The leader receives a real-time locating system (RTLS) signal from fixed Pozyx anchors and estimates its absolute position. The followers use low-cost LiDAR to measure the distance and bearing to nearby robots, then use wirelessly received neighbour positions to infer their own position. Every robot also runs an odometry-based estimate from its own gait-control history and IMU information. A neural network fuses this self-estimate with the finite-memory cooperative estimate, so the robots can benefit from the leader and from nearby peers without relying on either source alone." },
      { id: "paper-2-odometry", type: "callout", tone: "tip", heading: "Key term: Odometry", body: "Odometry is a robot’s estimate of where it has moved based on its own motion history. Here it is derived from gait-control variables such as step size and turning, corrected with the IMU’s pitch and roll measurements. It works even when an external sensor is disturbed by walking, but it drifts when the real movement no longer matches the commands - for example, if a person picks up and relocates the robot." },
      { id: "paper-2-flow", type: "mermaid", heading: "How the robots communicate and localize", body: "flowchart LR\n  A[RTLS anchors] --> B[Leader Robot 2\nabsolute position]\n  B <-->|WiFi: estimated position| C[Follower Robot 1]\n  B <-->|WiFi: estimated position| D[Follower Robot 3]\n  C <-->|WiFi when neighbours connect| D\n  C1[LiDAR + IMU] --> C\n  D1[LiDAR + IMU] --> D\n  B1[Odometry + IMU] --> B\n  C2[Odometry + IMU] --> C\n  D2[Odometry + IMU] --> D\n  B --> E[Each robot fuses cooperative and self estimates]\n  C --> E\n  D --> E\n  E --> F[Updated position for each robot]" },
      { id: "paper-2-sensors", type: "text", heading: "Leader, follower and sensor roles", body: "The leader is not simply followed physically; it is the better reference for localization. It carries a wireless tag for an RTLS based on a wireless sensor network and receives ranging signals from fixed anchors, giving it an absolute position. Each follower has a low-cost Cygbot LiDAR and an IMU. LiDAR supplies relative distance and bearing to neighbouring robots; the IMU supplies body heading for that relative measurement and pitch/roll for the odometry branch. All experimental robots also have a Raspberry Pi 4 and IMU. The experiment places RTLS anchors at the four corners of the 4.5 m square, while the measurement model uses ranging from three anchors to calculate the leader position." },
      { id: "paper-2-updates", type: "text", heading: "How position updates work", body: "The update is separate for each robot because every robot estimates its own x-y position. The leader’s cooperative branch is based on its own RTLS measurements; a follower’s cooperative branch combines its own LiDAR observation with the latest positions received from whatever neighbours are currently connected. All robots use the same stated algorithm settings: a 0.1 s sampling interval and a finite-memory window of N = 7 recent samples. The paper does not state a separate WiFi message interval, a per-robot communication schedule, or whether communication is asynchronous; it effectively assumes neighbour estimates are available at the sampling step." },
      { id: "paper-2-kidnapping", type: "text", heading: "Robot kidnapping and results", body: "Robot kidnapping means a person lifts a robot and places it somewhere else, so its commanded walking history no longer matches reality. In the test, Robots 1, 2 and 3 were moved at steps 100, 1050 and 800 respectively. Odometry-only localization struggles because it continues to trust its motion history. The fusion method recovers by incorporating external and cooperative measurements. Under normal motion, the proposed method reports root time-averaged errors of 0.0680 m, 0.0287 m and 0.0456 m for Robots 1-3. Under kidnapping, its errors are 0.0697 m, 0.0661 m and 0.0703 m; the odometry-only baseline rises to 0.6605 m for Robot 1." },
      { id: "paper-2-focus", type: "callout", tone: "warning", heading: "Main takeaway", body: "This paper is focused on keeping each humanoid robot’s position estimate correct. It uses communication only as a way to share neighbour positions for cooperative localization. It is not focused on handling network latency, packet loss, delay, bandwidth limits or unreliable WiFi." },
      { id: "paper-2-network", type: "text", heading: "Does it handle network issues?", body: "Network communication is required but not deeply studied. The robots use WiFi to exchange estimated positions, and the finite-memory method can use whichever neighbours are currently connected. However, the paper does not evaluate latency, packet loss, dropped messages, bandwidth limits, security attacks, synchronization errors or network recovery. It solves sensing and localization robustness, not communication robustness. Therefore, the method is a useful starting point for a multi-robot system, but its real-world reliability would still depend on a separate network design and tests under imperfect WiFi." },
      { id: "paper-2-feedback", type: "callout", tone: "warning", heading: "Feedback on the method", body: "This is a more focused and technically useful paper than a general humanoid demonstration because it identifies a real bipedal-robot problem: LiDAR is disturbed by body sway, while odometry fails after kidnapping. The sensor fusion idea is sensible and the experiment compares against several baselines. Its limits are the small three-robot indoor setup, fixed anchors, and the lack of a serious communication experiment. The claimed gains are credible for the tested setup, but they do not yet prove robustness for larger fleets or unreliable networks." },
    ],
  },
  {
    id: "paper-3",
    number: 6,
    slug: "o-races-open-ran-6g-humanoid-robots",
    title: "O-RACES",
    summary: "Proactive AI-driven scheduling in Open RAN for 6G-networked humanoid robots.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-3-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: O-RACES (Open RAN Real-time AI-Coordinated Efficient Scheduling)\n\nSummary: O-RACES is an important networked-robotics paper. It makes the wireless uplink predictable enough for edge-controlled humanoid locomotion by forecasting each robot’s upcoming traffic and reserving just the radio resources it needs before the robot asks for them. The key contribution is not a new humanoid controller; it is a practical Open RAN scheduling mechanism that improves latency and spectrum efficiency while scaling from 1 to 16 robot-control streams." },
      { id: "paper-3-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/o-races-open-ran-6g-humanoid-robots.pdf" },
      { id: "paper-3-status", type: "status", status: "pink", body: "Very important" },
      { id: "paper-3-summary", type: "text", heading: "My summary", body: "The authors place RL-trained locomotion policies in an AI Edge Cloud rather than on the humanoid. Each robot sends its sensor observation over the Open RAN uplink; the edge server produces the next joint-action command and returns it. Reactive scheduling waits until a robot requests uplink capacity, creating delay and jitter. O-RACES runs as a distributed app close to the Open RAN distributed unit, predicts the next 30 radio slots from the preceding 100 observations, and proactively assigns physical radio resources. This gives near-static-scheduling latency without permanently reserving the whole channel. The evaluation combines 16 virtual Unitree H1 robots in Isaac Sim with 16 physical modems and an experimental 3.75 GHz Open RAN testbed, so it is much closer to a real network experiment than a pure simulation." },
      { id: "paper-3-applications", type: "table", heading: "Applications and traffic in the paper", tableHeaders: ["Application", "How it is used"], tableRows: [["Centralized humanoid locomotion", "The primary use case: an edge-cloud RL policy controls whole-body walking over uneven terrain."], ["Intralogistics and industrial work", "The intended domain is cooperative humanoid work in warehouses, manufacturing floors and logistics hubs."], ["Rescue and rough-terrain mobility", "Used as a motivating application for robust dynamic locomotion, though not the central test scenario."], ["Visual localization", "Shown as a coexisting critical traffic flow in the Open RAN architecture."], ["Video and best-effort broadband", "Competing non-robot traffic used to test whether scheduling can preserve critical robot control while sharing spectrum."], ["Networked multi-robot control", "Up to 16 simultaneous robot-control streams test scalability and interference under shared wireless access."]] },
      { id: "paper-3-terms", type: "table", heading: "Key terms", tableHeaders: ["Term", "Definition"], tableRows: [["6G", "The next generation of mobile networks, here treated as a platform for ultra-low-latency, reliable industrial control."], ["Open RAN / O-RAN", "A disaggregated radio-access-network architecture with open interfaces, allowing software components such as schedulers to be added or changed."], ["O-RU", "Open Radio Unit: the radio hardware and lower radio functions near the antennas."], ["O-DU", "Open Distributed Unit: the near-radio compute unit that runs time-critical RAN functions and hosts the O-RACES dApp."], ["AI Edge Cloud (AI-EC)", "Compute infrastructure near the network edge that runs the robot-control policy without placing a powerful GPU on every robot."], ["Uplink", "Data travelling from the robot/user equipment to the base station and edge cloud; it is the paper’s main scheduling target."], ["Proactive scheduling", "Allocating radio resources before a packet requests them, based on a prediction of near-future traffic."], ["Reactive scheduling", "Allocating resources only after a robot requests them; this can add request, grant and queueing delay."], ["dApp", "A distributed application deployed close to the O-DU for fast, specialized Open RAN control."], ["PRB", "Physical Resource Block: a unit of radio time-frequency resources assigned to a user for transmission."], ["QoS", "Quality of Service: traffic prioritization rules that protect the robot-control flow over less critical traffic."], ["RL / PPO", "Reinforcement learning trains a controller through reward feedback; Proximal Policy Optimization is the algorithm used for the locomotion policy."], ["UE", "User Equipment: the modem/device connecting each robot-control stream to the mobile network."], ["E2E latency", "End-to-end delay from a robot observation being generated to the edge system receiving it; the paper measures the uplink application segment."], ["MAE", "Mean Absolute Error: here, the average difference between the commanded and actual robot velocity."]] },
      { id: "paper-3-ran", type: "text", heading: "Key term: RAN", body: "RAN means Radio Access Network: the part of a mobile network that connects user equipment (here, each robot’s physical modem) to the core and edge services. In this paper, the RAN includes the radio/base-station path and its Open RAN components—the O-RU, O-DU and O-CU. It receives robot observations over the uplink and, crucially, decides slot by slot how limited Physical Resource Blocks (PRBs) are assigned. O-RACES changes that scheduling decision near the O-DU, before robot packets arrive." },
      { id: "paper-3-metrics", type: "text", heading: "Metrics used to evaluate O-RACES", body: "The paper evaluates: application-level one-way uplink latency from a virtual robot’s observation packet to the AI Edge Cloud; latency distribution, including median and 99th-percentile tail latency; PRB allocation/usage as a measure of spectrum efficiency; MAC-layer data rate for each traffic class; velocity-tracking MAE; robot failure/fall rate during 60-second runs; and average total motor power. These metrics matter together: a scheduler can look fast while wasting all radio capacity, or save spectrum while making robot control unstable." },
      { id: "paper-3-results", type: "text", heading: "Main reported results", body: "O-RACES reduces median uplink latency by up to about 50% compared with reactive scheduling. At 16 robots it reports median latency between 6.3 and 7.6 ms, with 99th-percentile latency below 18 ms, while using 3.5% to 72.5% of PRBs. Static proactive scheduling reaches a 6 ms median but can consume 100% of available PRBs at 16 robots, starving other traffic. O-RACES reduces resource use by up to 40% versus that static approach and still keeps video traffic active. In control outcomes, O-RACES records no robot failures up to 8 robots and a 1.6% failure rate at 16 robots, versus up to 43.8% with reactive scheduling in the tested configurations." },
      { id: "paper-3-hybrid-testbed", type: "text", heading: "How the hybrid Isaac Sim and network test works", body: "Isaac Sim does not simulate the wireless network. It simulates the robot side: 16 virtual Unitree H1 humanoids (19 actuated joints) walk on randomized rough terrain in Isaac Sim 4.5. Each 6.67 ms simulation/control step (150 Hz), a robot produces an observation from its simulated IMU, joint position/velocity encoders and downward LiDAR terrain map. The observation is serialized and sent by UDP on that robot’s own socket to a dedicated physical modem. The packet then crosses a real 3.75 GHz indoor Open RAN base station, passes through the O-RU and O-DU/O-CU, and reaches the AI Edge Cloud, where the PPO locomotion policy calculates the joint-action vector. The response comes back through the same real mobile-network path and UDP socket; Isaac Sim applies the newest returned action to that virtual humanoid. There are 16 dedicated physical modem paths for the 16 virtual robots (within an 18-UE testbed). So physics, sensors and falls are virtual, but the uplink scheduling, radio contention, modem behaviour and edge-network transport are physical. To create congestion, the authors also inject physical video/localization and best-effort traffic. This is a hybrid experiment, not an Isaac-only network simulation." },
      { id: "paper-3-real-vs-virtual", type: "table", heading: "What is real hardware and what is virtual?", tableHeaders: ["Part", "What the paper actually uses", "Why it matters"], tableRows: [["Humanoid body and terrain", "Virtual: 1 to 16 Unitree H1 instances, their IMU, encoders, LiDAR, joint torques, walking, balancing and falls are simulated in Isaac Sim 4.5.", "It lets them safely repeat difficult rough-terrain walking with many robots, but it is not physical-robot validation."], ["Robot wireless endpoint", "Real: each virtual humanoid is paired one-to-one with a dedicated Quectel modem; 16 modems are used for 16 robot streams.", "Each robot’s control packets genuinely enter the mobile network rather than being placed into a software delay model."], ["Radio network", "Real: 18 physical UEs connect wirelessly to one indoor 3.75 GHz, 100 MHz Open RAN base station. The setup includes a Benetel RAN550 O-RU, fronthaul switch, and srsRAN O-DU/O-CU software running on an AMD Ryzen host.", "Radio scheduling, contention, interference and retransmissions occur in the real testbed and are measured in real time."], ["Core and edge control", "Real compute: an Open5GS core and a physical AI Edge Cloud server with an RTX 4090 run the trained locomotion policy. The AI-EC and UPF use 25 Gbps Ethernet to keep core transport delay low.", "The policy-inference and return-action path is a real closed loop, although its underlying robot is simulated."], ["Competing traffic", "Real test traffic: one physical UE produces 20 Mbps critical video/localization-like traffic and another produces best-effort congestion traffic using iPerf3/STING.", "This produces real competition for the same wireless resources rather than fake clock-time congestion."]] },
      { id: "paper-3-testbed-flow", type: "mermaid", heading: "Hybrid experiment: the actual control and network path", body: "flowchart LR\n  subgraph V[Virtual in Isaac Sim]\n    R[Unitree H1 physics\nrough terrain, balance, sensors]\n    O[150 Hz observation\nIMU, encoders, LiDAR]\n    A[Returned action applied\nto virtual joints]\n    R --> O\n    A --> R\n  end\n  subgraph P[Physical TU Dortmund research testbed]\n    M[Dedicated physical\nQuectel modem per robot]\n    B[Indoor 3.75 GHz\nOpen RAN base station]\n    D[O-RU and O-DU/O-CU\nsrsRAN plus O-RACES]\n    C[Open5GS core and\nAI Edge Cloud RTX 4090]\n    M -->|real radio uplink| B --> D --> C\n    C -->|real radio downlink| D --> B --> M\n  end\n  O -->|UDP packet| M\n  M -->|UDP action| A\n  X[Physical video and\nbackground traffic] --> B\n  style V fill:#eef6ff,stroke:#4f7cac\n  style P fill:#eef9f0,stroke:#4d8b5a\n  style X fill:#fff4e5,stroke:#cc8b3c" },
      { id: "paper-3-testbed-interpretation", type: "callout", tone: "tip", heading: "How to interpret this setup", body: "This is not a fully virtual network running in fake time. The robot world is virtual, but its 150 Hz control packets are sent through physical modems, an actual indoor radio cell, real Open RAN software/hardware, and a physical edge-compute server. The latency, PRB allocation, radio contention and retransmission results therefore come from real hardware in the loop. The authors are from TU Dortmund University and describe it as an experimental German industry-campus research testbed; the paper does not say that every listed component is university-owned. The main limitation is on the robotics side: a fall is a high-fidelity simulated fall, not a physical H1 falling in a warehouse." },
      { id: "paper-3-training", type: "text", heading: "Did the authors train the walking model themselves?", body: "Yes. The paper states that the authors train the locomotion controller themselves in Isaac Lab using RSL-RL and actor-critic Proximal Policy Optimization (PPO). They train 4,096 Unitree H1 instances in parallel on randomized uneven terrain. The policy receives proprioceptive state plus terrain information (IMU-derived motion/gravity, joint positions and velocities, the previous action, target velocity, and a 187-point downward-LiDAR height scan) and outputs 19 normalized target joint positions. A PD controller converts these targets into motor torques. Training rewards stable velocity tracking and gait/contact behaviour, while penalizing unstable orientation, overly abrupt actions, joint-limit violations and early episode termination from falling. The trained actor is then deployed at the AI Edge Cloud for evaluation; it is not a pre-trained black-box walking policy. Separately, the O-RACES traffic predictor is also trained by the authors: it is a lightweight DLinear model trained from traffic observations, not the PPO robot controller." },
      { id: "paper-3-failure-cases", type: "callout", tone: "warning", heading: "Where the experiment fails or becomes weak", body: "1. Reactive scheduling on difficult terrain: in the illustrated 2.6 m/s forward-walking run, high and variable network delay disturbs the control loop and the virtual robot falls after about 7 seconds. Across 60-second trials, reactive scheduling reaches failure rates up to 43.8% with 2 robots and 31.2% with 8 robots.\n\n2. High scale: all robots transmit together every 6.67 ms. With 16 robots this synchronized burst raises tail latency for every scheduler. O-RACES still has a 1.6% robot failure rate at 16 robots; it is not perfect.\n\n3. Interference and retransmissions: O-RACES can show latency outliers under radio interference/retransmissions. Prediction errors also produce a small median-latency increase and slightly worse velocity MAE than the fully static scheduler.\n\n4. Static scheduling: it keeps control stable by over-reserving radio resources, but at 16 robots it can consume 100% of PRBs and starve video/background traffic. It is stable, but not an efficient shared-network solution.\n\n5. What is not established: the robots are virtual and the setup is one indoor cell. The paper therefore does not demonstrate sim-to-real walking on physical humanoids, operation across changing cells, or performance against newer learned/predictive scheduler baselines." },
      { id: "paper-3-comparison-limit", type: "callout", tone: "warning", heading: "Important limitation: the baseline comparison is weak", body: "O-RACES is compared with reactive QoS-aware Round Robin scheduling and a static proactive pre-allocation scheme. These are useful deliberately different endpoints: reactive scheduling waits too long, while static allocation wastes capacity by reserving resources regardless of need. But the paper does not compare O-RACES head-to-head with newer proactive learned, predictive channel-aware, or reinforcement-learning schedulers. Therefore the results show that O-RACES is much better than these two baselines in this testbed, but they do not establish that it is better than the newest scheduling algorithms. For a paper making a strong 6G scheduling claim, this incomplete comparison is a real methodological weakness." },
      { id: "paper-3-feedback", type: "callout", tone: "tip", heading: "Why this paper matters", body: "Unlike a generic 6G vision paper, this work connects a concrete robotic control loop to a real Open RAN testbed and measures both network and robot outcomes. The limitation is that the humanoids are virtual Unitree H1 instances, not 16 physical robots, and the radio setting is one indoor testbed. Still, the Open RAN implementation, physical modems, edge policy loop and released measurement dataset make it a strong and useful reference for edge-controlled humanoid robotics." },
    ],
  },
  {
    id: "paper-4",
    number: 7,
    slug: "iot-humanoid-robot-review",
    title: "Use of Internet of Things in a Humanoid Robot",
    summary: "A review of the use of IoT in humanoid robots.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-4-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: To be added\n\nSummary: To be added" },
      { id: "paper-4-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/iot-humanoid-robot-review.pdf" },
      { id: "paper-4-status", type: "status", status: "red", body: "Not read yet" },
      { id: "paper-4-notes", type: "text", heading: "Notes", body: "Add reading notes, questions and useful connections here." },
    ],
  },
  {
    id: "paper-5",
    number: 8,
    slug: "internet-of-humanoids-survey",
    title: "The Internet of Humanoids",
    summary: "A survey of technologies, applications and challenges.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-5-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: IoH\n\nSummary: To be added" },
      { id: "paper-5-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/internet-of-humanoids-survey.pdf" },
      { id: "paper-5-status", type: "status", status: "red", body: "Not read yet" },
      { id: "paper-5-notes", type: "text", heading: "Notes", body: "Add reading notes, questions and useful connections here." },
    ],
  },
  {
    id: "paper-6",
    number: 9,
    slug: "vision-language-models-edge-robotic-perception",
    title: "Vision-Language Models on the Edge",
    summary: "Real-time robotic perception with edge-deployed vision-language models.",
    objectives: [],
    study: { definitions: [], questions: [] },
    status: "published",
    updatedAt: "2026-09-03T00:00:00.000Z",
    blocks: [
      { id: "paper-6-overview", type: "callout", tone: "note", heading: "Paper overview", body: "Abbreviation: VLMs\n\nSummary: To be added" },
      { id: "paper-6-file", type: "resource", heading: "Open paper", title: "Open PDF", body: "View the full research paper.", url: "/papers/vision-language-models-edge-robotic-perception.pdf" },
      { id: "paper-6-status", type: "status", status: "red", body: "Not read yet" },
      { id: "paper-6-notes", type: "text", heading: "Notes", body: "Add reading notes, questions and useful connections here." },
    ],
  },
];
